### ISSUE TITLE
两次点击下载时，第一次没有下载完，又会开始第二次下载

### ISSUE THREAD

**Issue by IdioticMadman** [a1018875550/retrofit-download-file#2]

**Comment by MichaelJokAr** [comment]
这个demo只是介绍如何用retrofit + rxjava下载文件并显示下载进度；其他的问题可以自己处理

**Comment by IdioticMadman** [comment]
有个问题不是很懂。就是这好像没怎么用到Retrofit和RxJava，其核心应该还是在用Okhttp。我这么说对么？

**Comment by MichaelJokAr** [comment]
retrofit底层的网络请求就是okhttp;至于那个第一次没有下载完，又会开始第二次下载的问题，欢迎修复提交
